main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('mascots/', views.mascots_index, name='index'),
  path('mascots/<int:mascot_id>/', views.mascots_detail, name="detail"),
  path('mascots/create/', views.MascotCreate.as_view(), name='mascots_create'),
  path('mascots/<int:pk>/update/', views.MascotUpdate.as_view(), name='mascots_update'),
  path('mascots/<int:pk>/delete/', views.MascotDelete.as_view(), name='mascots_delete'),
  path('mascots/<int:mascot_id>/add_feeding/', views.add_feeding, name='add_feeding'),
  path('mascots/<int:mascot_id>/assoc_product/<int:product_id>/', views.assoc_product, name='assoc_product'),
  path('products/', views.ProductList.as_view(), name='products_index'),
  path('products/<int:pk>/', views.ProductDetail.as_view(), name='products_detail'),
  path('products/create/', views.ProductCreate.as_view(), name='products_create'),
  path('products/<int:pk>/update/', views.ProductUpdate.as_view(), name='products_update'),
  path('products/<int:pk>/delete/', views.ProductDelete.as_view(), name='products_delete'),
]

mascotcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products_detail', kwargs={'pk': self.id})

class Mascot(models.Model):
    name = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    age = models.IntegerField()
    products = models.ManyToManyField(Product)

    def get_absolute_url(self):
      return reverse('detail', kwargs={'mascot_id': self.id})

MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)

class Feeding(models.Model):
  date = models.DateField()
  meal = models.CharField(
    max_length=1,
    choices=MEALS,
    default=MEALS[0][0]
  )

  mascot = models.ForeignKey(Mascot, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.get_meal_display()} on {self.date}"

  class Meta:
    ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
  class Meta:
    model = Feeding
    fields = ['date', 'meal']

main_app/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Mascot, Product
from .forms import FeedingForm
from django.views.generic import ListView, DetailView


# Define the home view
def home(request):
  return HttpResponse('<marquee  behavior="scroll" direction="left"><img src="/static/css/imgs/tony.jpg" alt="tony the tiger"></marquee>')

def about(request):
  return render(request, 'about.html')

def mascots_index(request):
  mascots = Mascot.objects.all()  
  return render(request, 'mascots/index.html', { 'mascots': mascots })

def mascots_detail(request, mascot_id):
  mascot = Mascot.objects.get(id=mascot_id)
  products_mascot_doesnt_endorse = Product.objects.exclude(id__in = mascot.products.all().values_list('id'))
  feeding_form = FeedingForm()
  return render(request, 'mascots/detail.html', {'mascot': mascot, 'feeding_form': feeding_form, 'products': products_mascot_doesnt_endorse})


def assoc_product(request, mascot_id, product_id ):
  mascot = Mascot.objects.get(id=mascot_id)
  mascot.products.add(product_id)
  return redirect('detail', mascot_id=mascot_id)

def add_feeding(request, mascot_id):
  form = FeedingForm(request.POST)
  if form.is_valid():
    new_feeding = form.save(commit=False)
    new_feeding.mascot_id = mascot_id
    new_feeding.save()
  return redirect('detail', mascot_id=mascot_id)

class MascotCreate(CreateView):
    model = Mascot
    fields = ['name', 'company', 'description', 'age']

class MascotUpdate(UpdateView):
  model = Mascot
  fields = ['company', 'description', 'age']

class MascotDelete(DeleteView):
  model = Mascot
  success_url = '/mascots/'

class ProductList(ListView):
  model = Product

class ProductDetail(DetailView):
  model = Product

class ProductCreate(CreateView):
  model = Product
  fields = '__all__'

class ProductUpdate(UpdateView):
  model = Product
  fields = ['name', 'color']

class ProductDelete(DeleteView):
  model = Product
  success_url = '/products/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Mascot Collector</h1>
<hr />
<p>Hire the Mascot Collector!</p>
<img src="/static/css/imgs/mascots.jpg" alt="mascots" class="left" width="100%" 
height="auto">

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Mascot Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Mascot Collector</a></li>
        </ul>
        <ul class="right">
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'products_create' %}">Add a Product</a></li>
            <li><a href="{% url 'products_index' %}">View All Products</a></li>
            <li><a href="{% url 'mascots_create' %}">Add a Mascot</a></li>
            <li><a href="{% url 'index' %}">View All My Mascots</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 Mascot Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/main_app/mascot_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Mascot</h1>

  <h4>Are you sure you want to delete <span class="white-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' mascot.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/mascot_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Mascot</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/product_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Product</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'products_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/product_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Product Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ product.name }}</span>
        <p>Color: {{ product.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'products_update' product.id %}">Edit</a>
        <a href="{% url 'products_delete' product.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/product_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Product</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
	<!-- Django requires the following for security purposes -->
	{% csrf_token %}
	<table>
		<!-- Render the inputs inside of <tr>s & <td>s -->
		{{ form.as_table }}
	</table>
	<input type="submit" value="Submit!" class="btn">
</form>
{% endblock %}

main_app/templates/main_app/product_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Product List</h1>

{% for product in product_list %}
  <a href="{% url 'products_detail' product.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ product.name }}</span>
            <p>Color: {{ product.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/mascots/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Mascot Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ mascot.name }}</span>
                <p>Company: {{ mascot.company }}</p>
                <p>Description: {{ mascot.description }}</p>
                <p>Age: {{ mascot.age }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'mascots_update' mascot.id %}">Edit</a>
                <a href="{% url 'mascots_delete' mascot.id %}">Delete</a>
            </div>
        </div>
    </div>
    <div class="col s6">
        <form action="{% url 'add_feeding' mascot.id %}" method="post">
            {% csrf_token %}
            {{ feeding_form.as_p }}
            <input type="submit" class="btn" value="Add Feeding">
        </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Meal</th>
                </tr>
            </thead>
            <tbody>
                {% for feeding in mascot.feeding_set.all %}
                <tr>
                    <td>{{feeding.date}}</td>
                    <td>{{feeding.get_meal_display}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<hr>
<div class="row">
    <div class="col s6">
        <h3>{{ mascot.name }}'s Products</h3>
        {% if mascot.products.count %}
        {% for product in mascot.products.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    A <span style="color: {{ product.color }}">{{ product.color }}</span> {{ product.name }}
                </span>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>No Products :(</h5>
        {% endif %}
    </div>
    <div class="col s6">
        <h3>Available Products</h3>
        {% if products.count %}
        {% for product in products.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    A <span style="color: {{ product.color }}">{{ product.color }}</span> {{ product.name }}
                </span>
            </div>
            <div class="card-action">
                <form action="{% url 'assoc_product' mascot.id product.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn">Add</button>
                </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>{{product.name}} Already Has All Products Available</h5>
        {% endif %}
    </div>
</div>

<script>
    const dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });

    const selectEl = document.getElementById('id_meal');
    M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/mascots/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Mascot List</h1>

{% for mascot in mascots %}
<div class="card">
    <a href="{% url 'detail' mascot.id %}">
        <div class="card=content">
            <span class="card-title">{{ mascot.name }}</span>
            <p>Company: {{ mascot.company }}</p>
            <p>Description: {{ mascot.description }}</p>
            <p>Age: {{ mascot.age }} </p>
        </div>
    </a>
</div>
{% endfor %}

{% endblock %}